name: Deploy React Build
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/react-flow.yml'
      - 'reactflow-app/**'
    branches-ignore:
      - 'master'
jobs:
  Deploy-React-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'pull_request' }}
        uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Deploying latest build
        run: sh ./deployReactBuild.sh
